### ISSUE TITLE
Braccio arm support for Gazebo

### ISSUE THREAD

**Issue by dpakshimpo** [ohlr/braccio_arduino_ros_gazebo#1]
Hello Ohlr,

Great work with this robot model support on Rviz and ROS. Would it be possible for you to add a model which can be loaded in Gazebo? I am trying a lot to get the spawned robot model to be stable in Gazebo, but no luck. The model continues to wobble and jiggle, even after adding Gazebo ROS controllers. Trial and error with PID values and damping and friction values is very cumbersome and inconsistent. I would be happy to share my XACRO code with you if you want to have a look at the XACRO and the controller files for Gazebo.

Thanks.

**Comment by ohlr** [comment]
Sorry for the late reply. But I have no experience in Gazebo (yet).
